# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-y				+= qpnp_adaptive_charge/
obj-y				+= qti_glink_charger/
obj-y				+= mmi_charger/
